CommandSet GrantCommandSet
    1     = Command_ToggleStance
    2     = Command_TogglePalantir1_MOS
    3     = Command_SpecialAbilitySettlement
    4     = Command_SpecialAbilityOutpost
    5     = Command_SpecialAbilityCamp
    6     = Command_SpecialAbilityCastle
    7     = Command_SpecialAbilityGrantExp
    8    = Command_SpecialAbilityGibPP
    9     = Command_FireWeaponMordorFortressSpireFireball_Boom
    10     = Command_SpecialAbilityISeeYou
    11     = Command_SpecialAbilityRestoration
    12     = Command_BigIndustry
    13     = Command_SpecialAbilitySpawnRing
    14     = Command_SpecialAbilitySpawnBadGuys
    16     = Command_SpecialAbilitySpawnTrees
    17     = Command_SpecialAbilityDominateEnemySarumanForever
    18     = Command_SauronModFiresOfDoom_Hack
    19     = Command_SpecialAbilitySpellbookRestoration
    20     = Command_CaptureBuilding
    21     = Command_AttackMove
    22     = Command_Stop
    23      = Command_SetStanceBattle
    24      = Command_SetStanceAggressive
    25     = Command_SetStanceHoldGround
End

CommandSet SpawnCommandSet
    1     = Command_ToggleStance
    2     = Command_TogglePalantir2_MOS
    3     = Command_PurchaseHauptclanFeuerbärte
    4     = Command_PurchaseHauptclanBreitschultern
    5     = Command_PurchaseHauptclanLangbärte
    ;7     = Command_SpecialAbilityRestorationMap
    8     = Command_KarshBlinkMapwide
    9     = Command_BilboMeisterdieb_Hack
    10    = Command_SpecialAbilityDrauglinMondsicheln_Hack
    12     = Command_CaptureBuilding
    13     = Command_AttackMove
    14     = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18     = Command_SetStanceHoldGround
End
